# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hummingbirdEMinternal <- function(normM, normUM, abnormM, abnormUM, pos, binSize) {
    .Call(`_hummingbird_hummingbirdEMinternal`, normM, normUM, abnormM, abnormUM, pos, binSize)
}

hummingbirdPostAdjustmentInternal <- function(em, pos, minCpGs, minLength, maxGap) {
    .Call(`_hummingbird_hummingbirdPostAdjustmentInternal`, em, pos, minCpGs, minLength, maxGap)
}

